apiVersion: v1
kind: Namespace
metadata:
  name: contacts
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: contacts
  labels:
    app: contacts
spec:
  selector:
    matchLabels:
      app: contacts
  replicas: 1
  template:
    metadata:
      labels:
        app: contacts
    spec:
      containers:
      - name: api-server
        image: $CONTACTS_REGISTRY/contacts-api
        imagePullPolicy: Always
        args:
        - -dsn
        - api:mypassword@tcp(mysql.db:3306)/contacts?charset=utf8&parseTime=True
        - -pdp
        - pdp.themis:5555
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: contacts
  labels:
    app: contacts
spec:
  type: NodePort
  selector:
    app: contacts
  ports:
  - name: http
    port: 80
    protocol: TCP
